# Change these first
owner: schaetzlein # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: EPLASS
    url: https://www.eplass.de
  - name: EPLASS Portal
    url: https://portal.eplass.de
  - name: SYSTEL Portal
    url: https://db-cde.eplass.de
  - name: EPLASS InfoClient
    url: https://infoclient.eplass.de
  - name: EPLASS File
    url: https://file.eplass.de
  - name: EPLASS Cloud
    url: https://cloud.eplass.de

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /upptime # where "repo" is your repository name
  name: upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: ocean
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
